Assignment/Models/Employee.cs
namespace Assignment.Models
{
    public class Employee
    {
       
            public int Id { get; set; }
            public string? Name { get; set; }
            public string? Department { get; set; }
            public double Salary { get; set; }
      


    }
}

Assignment/Models/EmployeeDLA.cs
using System.Data.SqlClient;
namespace Assignment.Models
{
    public class EmployeeDLA
    {

        SqlConnection con;
        SqlCommand cmd;
        SqlDataReader dr;
        IConfiguration configuration;
        public EmployeeDLA(IConfiguration configuration)
        {
            this.configuration = configuration;
            con = new SqlConnection(this.configuration.GetConnectionString("defaultConection"));
        }

        public List<Employee> GetEmployee()
        {
            List<Employee> list = new List<Employee>();
            string qry = "select * from employee1";
            cmd = new SqlCommand(qry, con);
            con.Open();
            dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    Employee e1 = new Employee();
                    e1.Id = Convert.ToInt32(dr["id"]);
                    e1.Name = dr["name"].ToString();
                    e1.Department =dr["department"].ToString();
                    e1.Salary = Convert.ToInt32(dr["salary"]);
                   


                    list.Add(e1);
                }
            }
            con.Close();
            return list;
        }
        public int AddEmployee(Employee e1)
        {
            int result = 0;
            string qry = "insert into employee1 values(@name,@department,@salary)";
            cmd = new SqlCommand(qry, con);
            cmd.Parameters.AddWithValue("@name", e1.Name);
            cmd.Parameters.AddWithValue("@department",e1.Department);
            cmd.Parameters.AddWithValue("@salary", e1.Salary);
            con.Open();
            result = cmd.ExecuteNonQuery();
            con.Close();
            return result;
        }
    }
}

Assignment/Models/ErrorViewModel.cs
namespace Assignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment/Models/Product.cs
namespace Assignment.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Price { get; set; }
    }
}

Assignment/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.InteropServices;

namespace Assignment.Controllers
{
    public class CourseController : Controller
    {       
            [HttpGet]

            public IActionResult CourseDetails()
            {
                List<string> Options = new List<string>()
            {
                "Java" , "C#" , "React" , "Angular" , "Software Testing"
            };

                ViewData["Options"] = new SelectList(Options);
                return View();
            }
            [HttpPost]
            public IActionResult CourseDetails(IFormCollection form)
            {
                
                ViewBag.Name = form["Name"];
                ViewBag.Gender = form["gender"];
                ViewBag.Options = form["Options"];
            ViewBag.course = form["course"];
                return View("DisplayCourseDetails");
            }
        }
    }
    

Assignment/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Assignment.Models;


namespace Assignment.Controllers
{
    public class EmployeeController : Controller
    {
        EmployeeDLA db;
        IConfiguration configuration;

        public EmployeeController(IConfiguration configuration)
        {
            this.configuration = configuration;
            db = new EmployeeDLA(this.configuration);
        }
        public IActionResult Index()
        {
            return View(db.GetEmployee());
        }
        public ActionResult Create()
        {
            return View();
        }

        // POST: CourseController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employee e1)
        {
            try
            {
                int result = db.AddEmployee(e1);
                if (result >= 1)
                {
                    return RedirectToAction(nameof(Index));//List 
                }
                else
                {
                    return View();//remain on create pages
                }

            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

Assignment/Controllers/HomeController.cs
using Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Assignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<string> colors = new List<string>()
            {
                "Red","White","Pink","Black","Yellow"
            };
            ViewData["list"] = colors; // implict --> object
            return View();

          
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assignment/Controllers/ProductController.cs
using Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;


public class ProductController : Controller
{
    public ActionResult Index()
    {
        
        List<Product> products = new List<Product>
        {
            new Product { Id = 1, Name = "Pen", Price = 20 },
            new Product { Id = 2, Name = "Pencil", Price =10 },
            new Product { Id = 3, Name = "Eraser", Price =2 }
        };

        
        ViewData["Message"] = "This is the product list";

        
        ViewBag.Products = products;

        return View();
    }
}

Assignment/Views/Course/CourseDetails.cshtml
@{
    ViewData["Title"] = "CourseDetails";
}

<h1>Course Details</h1>

@using (Html.BeginForm())
{
    <table>
       
        <tr>
            <td>Enter your Name</td>
            <td>
                @Html.TextBox("Name")
            </td>
        </tr>

        <tr>
            <td>Select Gender</td>
            <td>
                @Html.RadioButton("gender" , "Male") Male
                @Html.RadioButton("gender" , "Female") Female
            </td>
        </tr>



        


        <tr>
            <td>Select course</td>
            <td>
                <input type="checkbox" name="course" value="java" /> Java
                <input type="checkbox" name="course" value="C#" /> C#
                <input type="checkbox" name="course" value="React" />React
                <input type="checkbox" name="course" value="Software Teating" />Software Testing
                <input type="checkbox" name="course" value="Angular" />Angular
            </td>
        </tr>
        <tr>
            <td>Would you like to know more about the course?</td>
            <td>@Html.DropDownList("Options")</td>
        </tr>



        <tr>
            <td></td>
            <td>
                <input type="submit" value="save" />
            </td>
        </tr>

    </table>
}

Assignment/Views/Course/DisplayCourseDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "DisplayCourseDetails";
}

<h1>Display Course Details</h1>

<table class="table">
    <tr>
        <td>Name</td>
        <td>
            @ViewBag.Name
        </td>
    </tr>

    <tr>
        <td>Gender</td>
        <td>
            @ViewBag.Gender
        </td>
    </tr>


    <tr>
        <td>Course Option</td>
        <td>
            @ViewBag.Options
        </td>
    </tr>
    </tr>
    <tr>
        <td>Selected Course Details</td>
        <td>
            @foreach (string s in ViewBag.course)
            {
                <p>@s</p>
            }
        </td>
    </tr>


</table>

Assignment/Views/Employee/Create.cshtml
@model Assignment.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Assignment/Views/Employee/Index.cshtml
@model IEnumerable<Assignment.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Assignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Colors</h1>

@if (ViewData["list"] != null)
{
    <ol>
        @foreach (string str in (IEnumerable<string>)ViewData["list"])
        {
            <li>
                @str
            </li>
        }
    </ol>
}

Assignment/Views/Product/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewBag.Title = "Product List";
}

<h2>@ViewData["Message"]</h2>

<table class="table" >
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Price</th>
    </tr>
    @foreach (var product in ViewBag.Products)
    {
        <tr>
            <td>@product.Id</td>
            <td>@product.Name</td>
            <td>@product.Price.ToString()</td>
        </tr>
    }
</table>

Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Show Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="CourseDetails">Show Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index"> Add Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>